### ISSUE TITLE
x-www-form-urlencoded data in body

### ISSUE THREAD

**Issue by bbokun** [viniciusfbb/ipub-refit#5]
First of all - Your work is super! Thank You!

My problem is that I need to call a REST service in the following form

http://www.myserver.com/login/auth/oauth/token

which expects key/value pairs in the body (x-www-form-urlencoded)

When I do this in Postman everything works, but I did not manage to do this with ipub-refit

Authorization: 
Basic

Headers:
Content-Type:application/x-www-form-urlencoded
Accept:application/json

Body:
grant_type: password
username: myusername
password: mypassword

I trued this as follows

`[BaseUrl('http://www.myserver.com')]`
`[Headers('Accept', 'application/json')]`
`[Headers('Content-Type', 'application/x-www-form-urlencoded')]`
`IMyLogin = interface(IipRestApi)`
`['{C6FC4B3E-834D-4467-AC04-60C3DC21DACB}']`
`[Post('/login/auth/oauth/token')]`
`function postAccessToken(const ABody: string): string;`

And when I call the function with postAccessToken somehow the Body is empty.

With standard Delphi Classes, I would add the three parameters as pkGETorPOST Params to the TRESTRequest.

Is there any possibility to achieve this with iPub-refit?

Thanks in advance.

**Comment by GaNacereddine** [comment]
@bbokun you can follow what I did to add MultipartFormData body kind support.

look at the pull request I did and follow the same steps, and at the end you can have something like this

```
[BaseUrl(DefaultRESTAPIHost)]
[Headers('Content-Type', 'application/json')]
[Headers('Accept', 'application/json, text/plain; q=0.9, text/html;q=0.8,')]
IUserApi = interface(IipRestApi)
['{4F690615-D4AD-4BAF-9590-CC7D475C58DA}']
[Patch('/user')]
function UpdateUserData([Body(TBodyContentKind.MultipartFormData)] const AData: TMultipartFormData; 
                                          [Header('Authorization')] const AAuthToken: string): TUserResponse;
end;
```

**Comment by bbokun** [comment]
@GaNacereddine 
Thank You for Your reply. I will try it out, and if I find a solution I will inform You.

**Comment by viniciusfbb** [comment]
Hello. Recently I made several improvements to the lib and it is very simple to implement your api. I made an example of what the implementation of your api would look like.

Your rest api consumer unit:

```delphi
unit MyApiConsumer;

interface

uses
  System.SysUtils, iPub.Rtl.Refit; // https://github.com/viniciusfbb/ipub-refit

type
  TLoginGrantType = (Password);

  [BaseUrl('http://www.myserver.com')]
  IMyAPI= interface(IipRestApi)
    ['{C6FC4B3E-834D-4467-AC04-60C3DC21DACB}']

    [Post('/login/auth/oauth/token')]
    function TryLogin(const [Body] AGrant_type: TLoginGrantType; const [Body] AUsername, [Body] APassword: string; out AResponse: string): Boolean;

    [Get('/products')]
    [Headers('Authorization', 'Bearer {Token}')]
    function GetProducts: string; // This is an example of endpoint that needs authorization

    // We can freely declare properties with any name and of any type here, for use in queries or headers or simply storing values. To use in headers or urls you must specify in the header string or url value as follows: {PropertyName}
    function GetToken: string;
    procedure SetToken(const AValue: string);
    property Token: string read GetToken write SetToken;
  end;

var
  FMyApi: IMyAPI;

implementation

initialization
  FMyApi := GRestService.&For<IMyAPI>;
end.
```

And in your code:

```delphi
uses
  MyApiConsumer;

procedure TForm1.FormCreate(Sender: TObject);
var
  LToken: string;
begin
  if FMyApi.TryLogin(TLoginGrantType.Password, 'login', 'password', LToken) then
  begin
    FMyApi.Token := LToken;
    ShowMessage(FMyApi.GetProducts); // Accessing an endpoint that needs this authorization
  end;
end;
```

**Comment by viniciusfbb** [comment]
The problem is solved with the code above. I will close the issue for lack of feedback but feel free to open another one about this or any other subject.

**Comment by bbokun** [comment]
> The problem is solved with the code above. I will close the issue for lack of feedback but feel free to open another one about this or any other subject.

Hello, 
sorry for not giving feedback, I did not realize that there were changes made. I checked out Your solution, and it works like a charm.
Thank You!
